### ISSUE TITLE
No attribute 'parse_ticks', possible Issues installing latest version

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/Python-demoparser#5]
I was running into some issues running some of the examples. I was getting errors like.

`AttributeError: 'builtins.DemoParser' object has no attribute 'parse_ticks'`

But I then noticed the version of the package I was on was 0.1.0 when the latest appears to be 0.3.2.
So I uninstalled an reinstalled demoparser.

```
pip install demoparser
Collecting demoparser
  Downloading demoparser-0.1.0.tar.gz (336 kB)
```

But it just re-downloads the 0.10 version.
So I tried to specify the latest version.

```
pip install demoparser==0.3.2
ERROR: Could not find a version that satisfies the requirement demoparser==0.3.2 (from versions: 0.1.0)
ERROR: No matching distribution found for demoparser==0.3.2
```

This appears to be mac specific. I am able to install the newest version just fine on a windows machine. I also see .whl files available for windows and linux. But none for macos.

**Comment by LaihoE** [comment]
Could you check if it works with 0.3.3?. I think there must of been a build I created sometime in the beginning that had a mac build also, thats why it tried to download 0.10.

**Comment by DandrewsDev** [comment]
I was able to confirm that I can now download 0.3.3 on Macos, and its working as expected.
